# Generated by Django 6.0.5 on 2026-05-16 14:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used to login', max_length=254, unique=True, verbose_name='Email address ')),
                ('name', models.CharField(help_text='What should we call you?', max_length=100, verbose_name='Full name')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Please enter a valid phone number')], verbose_name='Phone number')),
                ('is_tenant', models.BooleanField(default=True, help_text='Can view and accommodations', verbose_name='Tenant')),
                ('is_landlord', models.BooleanField(default=False, help_text='Can create and manage ads', verbose_name='Landlord')),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('both', 'Tenant and Landlord'), ('admin', 'Administrator')], default='tenant', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the user should have access', verbose_name='Activ')),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into the admin panel', verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of registration')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['is_tenant', 'is_landlord'], name='users_is_tena_b2cf12_idx')],
            },
        ),
    ]
