# Generated by Django 6.0.5 on 2026-05-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Search keyword')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Searched at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['keyword'], name='search_hist_keyword_03b4bf_idx'), models.Index(fields=['user', 'searched_at'], name='search_hist_user_id_f49661_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed at')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_history', to='properties.property', verbose_name='Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'View History',
                'verbose_name_plural': 'View Histories',
                'db_table': 'view_history',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['listing', 'user', 'viewed_at'], name='view_histor_listing_9317c7_idx')],
            },
        ),
    ]
