# Generated by Django 6.0.5 on 2026-05-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name of the type of housing')),
            ],
            options={
                'verbose_name': 'Type of housing',
                'verbose_name_plural': 'Types of housing',
                'db_table': 'property_types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Headline')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=255, verbose_name='Full address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night (€)')),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Number of rooms')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available from')),
                ('min_rental_period', models.IntegerField(default=1, verbose_name='Minimum rental period nights')),
                ('images', models.JSONField(default=list, help_text='List of images URL in AWS S3', verbose_name='Images')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rented', 'Rented'), ('deleted', 'Deleted')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('views_count', models.IntegerField(default=0, verbose_name='Number of views')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletion date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='common.city', verbose_name='City')),
                ('owner', models.ForeignKey(limit_choices_to={'is_landlord': True}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Landlord')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype', verbose_name='Type of housing')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'properties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='properties_status_e6008a_idx'), models.Index(fields=['location'], name='properties_locatio_5aa25a_idx'), models.Index(fields=['price'], name='properties_price_aa33af_idx'), models.Index(fields=['rooms'], name='properties_rooms_2a7dc8_idx')],
            },
        ),
    ]
