# Generated by Django 6.0.5 on 2026-05-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average rating'),
        ),
    ]
